import {
  AcademicValidationStatus,
  ApplicationStatus,
  CertificateStatus,
  DeliverableStatus,
  FeedbackSource,
  ProjectStatus,
  ProjectType,
  StudentLevel,
  StudentSubLevel,
  TaskStatus,
  UserRole,
} from "@prisma/client";

export const DEMO_PASSWORD = "DevPass123!";

export const seedUsers = {
  admin: {
    email: "admin@demo.resilience.local",
    firstName: "Ines",
    lastName: "Mansouri",
    role: UserRole.ADMIN,
    phone: "+21670000001",
  },
  supervisors: [
    {
      email: "supervisor.archi@demo.resilience.local",
      firstName: "Karim",
      lastName: "Ben Salem",
      role: UserRole.SUPERVISOR,
      phone: "+21670000011",
      title: "Lead Software Architect",
      department: "Pedagogie Produit",
      expertiseArea: "Architecture web et engineering leadership",
      organization: "Resilience Lab",
    },
    {
      email: "supervisor.data@demo.resilience.local",
      firstName: "Salma",
      lastName: "Gharbi",
      role: UserRole.SUPERVISOR,
      phone: "+21670000012",
      title: "Data & Delivery Mentor",
      department: "Suivi Projets",
      expertiseArea: "Data products, QA et delivery agile",
      organization: "Resilience Lab",
    },
  ],
  companies: [
    {
      email: "contact@novacraft.demo.resilience.local",
      firstName: "Youssef",
      lastName: "Trabelsi",
      role: UserRole.COMPANY,
      phone: "+21670000021",
      jobTitle: "Digital Product Manager",
      department: "Innovation",
      company: {
        name: "NovaCraft Studio",
        website: "https://novacraft.demo.local",
        description:
          "Studio digital qui conçoit des plateformes SaaS B2B pour la logistique et l'ops.",
        industry: "SaaS logistique",
      },
    },
    {
      email: "partnerships@greenloop.demo.resilience.local",
      firstName: "Meriem",
      lastName: "Jebali",
      role: UserRole.COMPANY,
      phone: "+21670000022",
      jobTitle: "Head of Partnerships",
      department: "Operations",
      company: {
        name: "GreenLoop Systems",
        website: "https://greenloop.demo.local",
        description:
          "Entreprise climate-tech focalisée sur la traçabilité des déchets et le reporting ESG.",
        industry: "Climate Tech",
      },
    },
  ],
  students: [
    {
      email: "amal.bensaid@demo.resilience.local",
      firstName: "Amal",
      lastName: "Bensaid",
      phone: "+21671110001",
      level: StudentLevel.LEVEL_1,
      subLevel: StudentSubLevel.LEVEL_1_FOUNDATION,
      headline: "Frontend trainee focused on accessible interfaces",
      bio: "Etudiante curieuse qui consolide ses bases React, TypeScript et accessibilite web via des projets guides.",
      skillsSummary: "HTML semantique, CSS responsive, React, TypeScript debutant, GitHub Flow",
      academicInstitution: "Institut Numerique Demo",
      programName: "Licence Genie Logiciel",
      graduationYear: 2027,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/amal-bensaid.pdf",
      githubUrl: "https://github.demo.local/amal-bensaid",
      linkedinUrl: "https://linkedin.demo.local/in/amal-bensaid",
      portfolioUrl: "https://portfolio.demo.local/amal-bensaid",
      isPortfolioPublic: false,
      portfolioSlug: "amal-bensaid",
    },
    {
      email: "rayan.haddad@demo.resilience.local",
      firstName: "Rayan",
      lastName: "Haddad",
      phone: "+21671110002",
      level: StudentLevel.LEVEL_1,
      subLevel: StudentSubLevel.LEVEL_1_DELIVERY,
      headline: "Junior full-stack builder with strong execution habits",
      bio: "Aime transformer une specification simple en application livrable avec une attention particuliere pour les tests et la clarte du code.",
      skillsSummary: "Next.js, Node.js, Prisma, PostgreSQL bases, tests unitaires",
      academicInstitution: "Institut Numerique Demo",
      programName: "Licence Genie Logiciel",
      graduationYear: 2026,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/rayan-haddad.pdf",
      githubUrl: "https://github.demo.local/rayan-haddad",
      linkedinUrl: "https://linkedin.demo.local/in/rayan-haddad",
      portfolioUrl: "https://portfolio.demo.local/rayan-haddad",
      isPortfolioPublic: true,
      portfolioSlug: "rayan-haddad",
    },
    {
      email: "nour.masmoudi@demo.resilience.local",
      firstName: "Nour",
      lastName: "Masmoudi",
      phone: "+21671110003",
      level: StudentLevel.LEVEL_1,
      subLevel: StudentSubLevel.LEVEL_1_TRANSITION,
      headline: "Product-minded student moving from guided work to initiative",
      bio: "Travaille sur des projets pedagogiques plus ouverts et commence a proposer des ameliorations produit en autonomie.",
      skillsSummary: "UI design systems, React Query notions, API integration, Figma handoff",
      academicInstitution: "Ecole Demo des Technologies",
      programName: "Cycle Ingenieur Informatique",
      graduationYear: 2027,
      academicValidationStatus: AcademicValidationStatus.IN_REVIEW,
      cvUrl: "https://assets.demo.local/cv/nour-masmoudi.pdf",
      githubUrl: "https://github.demo.local/nour-masmoudi",
      linkedinUrl: "https://linkedin.demo.local/in/nour-masmoudi",
      portfolioUrl: "https://portfolio.demo.local/nour-masmoudi",
      isPortfolioPublic: false,
      portfolioSlug: "nour-masmoudi",
    },
    {
      email: "mehdi.fekih@demo.resilience.local",
      firstName: "Mehdi",
      lastName: "Fekih",
      phone: "+21671110004",
      level: StudentLevel.LEVEL_2,
      subLevel: StudentSubLevel.LEVEL_2_CONTRIBUTOR,
      headline: "Backend contributor on real delivery squads",
      bio: "Contribue sur des APIs Node et des schemas de donnees avec un bon sens de la qualite et de la revue de code.",
      skillsSummary: "Node.js, Express, Prisma, PostgreSQL, API REST, Docker bases",
      academicInstitution: "Ecole Demo des Technologies",
      programName: "Cycle Ingenieur Informatique",
      graduationYear: 2026,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/mehdi-fekih.pdf",
      githubUrl: "https://github.demo.local/mehdi-fekih",
      linkedinUrl: "https://linkedin.demo.local/in/mehdi-fekih",
      portfolioUrl: "https://portfolio.demo.local/mehdi-fekih",
      isPortfolioPublic: true,
      portfolioSlug: "mehdi-fekih",
    },
    {
      email: "sarra.kefi@demo.resilience.local",
      firstName: "Sarra",
      lastName: "Kefi",
      phone: "+21671110005",
      level: StudentLevel.LEVEL_2,
      subLevel: StudentSubLevel.LEVEL_2_EXECUTION,
      headline: "Execution-focused product engineer for live client projects",
      bio: "A de bonnes habitudes de delivery, suit les priorites business et sait communiquer clairement sur l'avancement.",
      skillsSummary: "Next.js, TypeScript, schema design, integration testing, agile delivery",
      academicInstitution: "Faculte Demo des Sciences",
      programName: "Master Ingenierie Logicielle",
      graduationYear: 2025,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/sarra-kefi.pdf",
      githubUrl: "https://github.demo.local/sarra-kefi",
      linkedinUrl: "https://linkedin.demo.local/in/sarra-kefi",
      portfolioUrl: "https://portfolio.demo.local/sarra-kefi",
      isPortfolioPublic: false,
      portfolioSlug: "sarra-kefi",
    },
    {
      email: "ilyes.chaabane@demo.resilience.local",
      firstName: "Ilyes",
      lastName: "Chaabane",
      phone: "+21671110006",
      level: StudentLevel.LEVEL_2,
      subLevel: StudentSubLevel.LEVEL_2_CONTRIBUTOR,
      headline: "Data-oriented engineer contributing to analytics and ops tooling",
      bio: "Intervient sur des pipelines de donnees legers et sur des tableaux de bord internes pour des equipes operations.",
      skillsSummary: "SQL, dbt notions, Python scripts, BI dashboards, QA data",
      academicInstitution: "Institut Numerique Demo",
      programName: "Master Data & Software",
      graduationYear: 2025,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/ilyes-chaabane.pdf",
      githubUrl: "https://github.demo.local/ilyes-chaabane",
      linkedinUrl: "https://linkedin.demo.local/in/ilyes-chaabane",
      portfolioUrl: "https://portfolio.demo.local/ilyes-chaabane",
      isPortfolioPublic: false,
      portfolioSlug: "ilyes-chaabane",
    },
    {
      email: "leila.hammami@demo.resilience.local",
      firstName: "Leila",
      lastName: "Hammami",
      phone: "+21671110007",
      level: StudentLevel.LEVEL_3,
      subLevel: StudentSubLevel.LEVEL_3_AUTONOMOUS,
      headline: "Autonomous software engineer ready for scoped missions",
      bio: "Travaille en quasi autonomie, sait cadrer des livrables, arbitrer techniquement et presenter ses choix a un interlocuteur metier.",
      skillsSummary: "System design basics, Next.js, Prisma, observability, secure API design",
      academicInstitution: "Faculte Demo des Sciences",
      programName: "Master Ingenierie Logicielle",
      graduationYear: 2025,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/leila-hammami.pdf",
      githubUrl: "https://github.demo.local/leila-hammami",
      linkedinUrl: "https://linkedin.demo.local/in/leila-hammami",
      portfolioUrl: "https://portfolio.demo.local/leila-hammami",
      isPortfolioPublic: true,
      portfolioSlug: "leila-hammami",
    },
    {
      email: "omar.kallel@demo.resilience.local",
      firstName: "Omar",
      lastName: "Kallel",
      phone: "+21671110008",
      level: StudentLevel.LEVEL_3,
      subLevel: StudentSubLevel.LEVEL_3_LEADERSHIP,
      headline: "Advanced student leading delivery and peer coordination",
      bio: "Prend des sujets transverses, accompagne d'autres etudiants et maintient un bon niveau de qualite sur des missions avancees.",
      skillsSummary: "Technical leadership, code review, performance profiling, API contracts, stakeholder sync",
      academicInstitution: "Ecole Demo des Technologies",
      programName: "Cycle Ingenieur Informatique",
      graduationYear: 2025,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/omar-kallel.pdf",
      githubUrl: "https://github.demo.local/omar-kallel",
      linkedinUrl: "https://linkedin.demo.local/in/omar-kallel",
      portfolioUrl: "https://portfolio.demo.local/omar-kallel",
      isPortfolioPublic: true,
      portfolioSlug: "omar-kallel",
    },
    {
      email: "hana.bouzid@demo.resilience.local",
      firstName: "Hana",
      lastName: "Bouzid",
      phone: "+21671110009",
      level: StudentLevel.LEVEL_1,
      subLevel: StudentSubLevel.LEVEL_1_FOUNDATION,
      headline: "Careful junior builder focused on product clarity",
      bio: "Renforce ses bases sur des produits pedagogiques simples et cherche surtout a livrer un parcours propre, lisible et fiable.",
      skillsSummary: "HTML, CSS, React debutant, wireframing, tests manuels",
      academicInstitution: "Institut Numerique Demo",
      programName: "Licence Genie Logiciel",
      graduationYear: 2027,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/hana-bouzid.pdf",
      githubUrl: "https://github.demo.local/hana-bouzid",
      linkedinUrl: "https://linkedin.demo.local/in/hana-bouzid",
      portfolioUrl: "https://portfolio.demo.local/hana-bouzid",
      isPortfolioPublic: false,
      portfolioSlug: "hana-bouzid",
    },
    {
      email: "yassine.dridi@demo.resilience.local",
      firstName: "Yassine",
      lastName: "Dridi",
      phone: "+21671110010",
      level: StudentLevel.LEVEL_1,
      subLevel: StudentSubLevel.LEVEL_1_DELIVERY,
      headline: "Delivery-oriented learner building confidence through MVPs",
      bio: "Aime les projets concrets a portee claire et progresse vite quand il peut relier UI, logique metier simple et feedback terrain.",
      skillsSummary: "TypeScript debutant, React, API integration basics, QA checklist, Git",
      academicInstitution: "Ecole Demo des Technologies",
      programName: "Cycle Preparatoire Informatique",
      graduationYear: 2027,
      academicValidationStatus: AcademicValidationStatus.VALIDATED,
      cvUrl: "https://assets.demo.local/cv/yassine-dridi.pdf",
      githubUrl: "https://github.demo.local/yassine-dridi",
      linkedinUrl: "https://linkedin.demo.local/in/yassine-dridi",
      portfolioUrl: "https://portfolio.demo.local/yassine-dridi",
      isPortfolioPublic: false,
      portfolioSlug: "yassine-dridi",
    },
  ],
};

export const seedProjects = [
  {
    key: "l1-campus-helpdesk",
    title: "Campus Helpdesk Portal",
    summary: "Portail pedagogique de tickets internes pour un service support universitaire fictif.",
    description:
      "Le projet consiste a construire un portail simple pour creer, suivre et cloturer des tickets de support etudiant avec priorites, commentaires et statistiques de base.",
    type: ProjectType.FICTIONAL,
    status: ProjectStatus.IN_PROGRESS,
    targetLevel: StudentLevel.LEVEL_1,
    capacity: 3,
    supervisorEmail: "supervisor.archi@demo.resilience.local",
    companyName: null,
    createdByEmail: "admin@demo.resilience.local",
  },
  {
    key: "l1-library-availability",
    title: "Library Seat Availability Tracker",
    summary: "Application fictive de suivi d'occupation des espaces de travail d'une bibliotheque.",
    description:
      "Les etudiants doivent produire un MVP web responsive pour consulter les salles, les postes disponibles et les plages de forte affluence.",
    type: ProjectType.FICTIONAL,
    status: ProjectStatus.OPEN,
    targetLevel: StudentLevel.LEVEL_1,
    capacity: 3,
    supervisorEmail: "supervisor.data@demo.resilience.local",
    companyName: null,
    createdByEmail: "admin@demo.resilience.local",
  },
  {
    key: "l1-student-budget",
    title: "Student Budget Companion",
    summary: "Produit fictif aidant des etudiants a piloter un budget mensuel et des objectifs d'epargne.",
    description:
      "Le scope couvre l'authentification simple, un tableau des depenses, des categories et des alertes budgetaires pedagogiques.",
    type: ProjectType.FICTIONAL,
    status: ProjectStatus.OPEN,
    targetLevel: StudentLevel.LEVEL_1,
    capacity: 2,
    supervisorEmail: "supervisor.archi@demo.resilience.local",
    companyName: null,
    createdByEmail: "admin@demo.resilience.local",
  },
  {
    key: "l2-novacraft-ops-hub",
    title: "NovaCraft Ops Hub",
    summary: "Back-office reel pour centraliser incidents, disponibilites et suivi d'execution logistique.",
    description:
      "Projet reel B2B pour construire un tableau de bord operations avec priorisation d'incidents, SLA et journal d'activite.",
    type: ProjectType.REAL,
    status: ProjectStatus.IN_PROGRESS,
    targetLevel: StudentLevel.LEVEL_2,
    capacity: 3,
    supervisorEmail: "supervisor.archi@demo.resilience.local",
    companyName: "NovaCraft Studio",
    createdByEmail: "contact@novacraft.demo.resilience.local",
  },
  {
    key: "l2-greenloop-reporting",
    title: "GreenLoop ESG Reporting Workspace",
    summary: "Espace de suivi des indicateurs de recyclage et de reporting ESG pour clients enterprise.",
    description:
      "Le produit cible la collecte d'indicateurs, la visualisation des tendances et l'export d'un reporting mensuel propre.",
    type: ProjectType.REAL,
    status: ProjectStatus.OPEN,
    targetLevel: StudentLevel.LEVEL_2,
    capacity: 3,
    supervisorEmail: "supervisor.data@demo.resilience.local",
    companyName: "GreenLoop Systems",
    createdByEmail: "partnerships@greenloop.demo.resilience.local",
  },
  {
    key: "l3-greenloop-audit-trail",
    title: "GreenLoop Audit Trail Console",
    summary: "Console interne pour tracer les changements de donnees sensibles et fiabiliser les audits produit.",
    description:
      "Le projet demande un niveau serieux de modelisation de donnees, de journalisation et de clarification des responsabilites entre utilisateurs.",
    type: ProjectType.REAL,
    status: ProjectStatus.DRAFT,
    targetLevel: StudentLevel.LEVEL_3,
    capacity: 2,
    supervisorEmail: "supervisor.archi@demo.resilience.local",
    companyName: "GreenLoop Systems",
    createdByEmail: "partnerships@greenloop.demo.resilience.local",
  },
  {
    key: "l1-campus-event-checkin",
    title: "Campus Event Check-in Companion",
    summary: "Application pedagogique de check-in pour evenements et ateliers etudiants.",
    description:
      "Le MVP couvre la gestion d'inscriptions, un check-in QR simplifie, une liste de presence et une vue de suivi des capacites.",
    type: ProjectType.FICTIONAL,
    status: ProjectStatus.OPEN,
    targetLevel: StudentLevel.LEVEL_1,
    capacity: 3,
    supervisorEmail: "supervisor.data@demo.resilience.local",
    companyName: null,
    createdByEmail: "admin@demo.resilience.local",
  },
  {
    key: "l1-study-group-scheduler",
    title: "Study Group Scheduler",
    summary: "Produit pedagogique pour organiser des groupes d'etude, leurs sessions et leurs disponibilites.",
    description:
      "Le projet demande un planning simple, des invitations internes, une gestion de creneaux et un suivi de participation.",
    type: ProjectType.FICTIONAL,
    status: ProjectStatus.OPEN,
    targetLevel: StudentLevel.LEVEL_1,
    capacity: 3,
    supervisorEmail: "supervisor.archi@demo.resilience.local",
    companyName: null,
    createdByEmail: "admin@demo.resilience.local",
  },
  {
    key: "l3-autonomous-platform-hardening",
    title: "Autonomous Platform Hardening Mission",
    summary: "Mission avancee d'autonomie sur la fiabilisation d'une plateforme Next.js/Prisma existante.",
    description:
      "Mission de niveau 3 orientee ownership: securite applicative, observabilite, robustesse des workflows Prisma et reduction des incidents de production.",
    type: ProjectType.REAL,
    status: ProjectStatus.IN_PROGRESS,
    targetLevel: StudentLevel.LEVEL_3,
    capacity: 2,
    supervisorEmail: "supervisor.data@demo.resilience.local",
    companyName: "NovaCraft Studio",
    createdByEmail: "admin@demo.resilience.local",
  },
] as const;

export const projectApplications = [
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "amal.bensaid@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Je veux pratiquer la gestion d'etat front et apprendre a transformer une specification support en produit simple.",
    reviewedByEmail: "supervisor.archi@demo.resilience.local",
  },
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "rayan.haddad@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Le projet me permet de consolider le full-stack et la modelisation Prisma sur un cas pedagogique concret.",
    reviewedByEmail: "supervisor.archi@demo.resilience.local",
  },
  {
    projectKey: "l1-library-availability",
    studentEmail: "nour.masmoudi@demo.resilience.local",
    status: ApplicationStatus.SHORTLISTED,
    motivation: "Je peux contribuer sur la couche interface et la conception d'une experience claire pour les usagers.",
    reviewedByEmail: "supervisor.data@demo.resilience.local",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Je suis motive par un back-office reel avec contraintes d'operations et exigences de fiabilite.",
    reviewedByEmail: "contact@novacraft.demo.resilience.local",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "sarra.kefi@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Le contexte B2B et la proximite avec des besoins operations me correspondent tres bien.",
    reviewedByEmail: "contact@novacraft.demo.resilience.local",
  },
  {
    projectKey: "l2-greenloop-reporting",
    studentEmail: "ilyes.chaabane@demo.resilience.local",
    status: ApplicationStatus.PENDING,
    motivation: "Je veux contribuer sur les flux data et le reporting d'indicateurs avec un vrai enjeu metier.",
    reviewedByEmail: null,
  },
  {
    projectKey: "l2-greenloop-reporting",
    studentEmail: "sarra.kefi@demo.resilience.local",
    status: ApplicationStatus.WITHDRAWN,
    motivation: "Je me suis positionnee au depart mais je privilegie finalement un autre projet pour des raisons de charge.",
    reviewedByEmail: "partnerships@greenloop.demo.resilience.local",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "leila.hammami@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Cette mission est ideale pour demontrer mon autonomie sur la securite et la fiabilite d'une plateforme existante.",
    reviewedByEmail: "supervisor.data@demo.resilience.local",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "omar.kallel@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Je veux porter un sujet transverse, cadrer les chantiers et aider a industrialiser la qualite d'execution.",
    reviewedByEmail: "admin@demo.resilience.local",
  },
  {
    projectKey: "l1-campus-event-checkin",
    studentEmail: "hana.bouzid@demo.resilience.local",
    status: ApplicationStatus.PENDING,
    motivation: "Je veux travailler sur un MVP simple avec des interactions concretes, de la validation de flux et une logique produit claire.",
    reviewedByEmail: null,
  },
  {
    projectKey: "l1-study-group-scheduler",
    studentEmail: "yassine.dridi@demo.resilience.local",
    status: ApplicationStatus.ACCEPTED,
    motivation: "Le sujet correspond bien a mon niveau et me permet de progresser sur un parcours complet entre interface, logique simple et feedback superviseur.",
    reviewedByEmail: "supervisor.archi@demo.resilience.local",
  },
] as const;

export const memberships = [
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "amal.bensaid@demo.resilience.local",
    assignedByEmail: "supervisor.archi@demo.resilience.local",
    roleLabel: "Frontend owner",
  },
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "rayan.haddad@demo.resilience.local",
    assignedByEmail: "supervisor.archi@demo.resilience.local",
    roleLabel: "API & schema owner",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    assignedByEmail: "contact@novacraft.demo.resilience.local",
    roleLabel: "Backend contributor",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "sarra.kefi@demo.resilience.local",
    assignedByEmail: "contact@novacraft.demo.resilience.local",
    roleLabel: "Product engineer",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "leila.hammami@demo.resilience.local",
    assignedByEmail: "supervisor.data@demo.resilience.local",
    roleLabel: "Reliability lead",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "omar.kallel@demo.resilience.local",
    assignedByEmail: "admin@demo.resilience.local",
    roleLabel: "Delivery coordinator",
  },
  {
    projectKey: "l1-study-group-scheduler",
    studentEmail: "yassine.dridi@demo.resilience.local",
    assignedByEmail: "supervisor.archi@demo.resilience.local",
    roleLabel: "Planning and UI integrator",
  },
] as const;

export const projectTasks = [
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "amal.bensaid@demo.resilience.local",
    createdByEmail: "supervisor.archi@demo.resilience.local",
    title: "Implement ticket creation flow",
    description: "Construire le formulaire de creation de ticket avec priorite, categorie et validation des champs.",
    status: TaskStatus.IN_PROGRESS,
    dueDate: "2026-05-20T10:00:00.000Z",
  },
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "rayan.haddad@demo.resilience.local",
    createdByEmail: "supervisor.archi@demo.resilience.local",
    title: "Model support tickets in Prisma",
    description: "Definir les entites ticket, commentaire et SLA dans le schema de developpement.",
    status: TaskStatus.DONE,
    dueDate: "2026-05-15T10:00:00.000Z",
    completedAt: "2026-05-14T16:00:00.000Z",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    createdByEmail: "contact@novacraft.demo.resilience.local",
    title: "Design incident intake API",
    description: "Concevoir l'API REST pour la creation d'incidents et la qualification initiale par les operations.",
    status: TaskStatus.IN_PROGRESS,
    dueDate: "2026-05-18T09:00:00.000Z",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "sarra.kefi@demo.resilience.local",
    createdByEmail: "supervisor.archi@demo.resilience.local",
    title: "Build operations dashboard overview",
    description: "Produire la vue d'ensemble incidents, SLA et disponibilite equipe avec filtres de base.",
    status: TaskStatus.TODO,
    dueDate: "2026-05-22T09:00:00.000Z",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "leila.hammami@demo.resilience.local",
    createdByEmail: "supervisor.data@demo.resilience.local",
    title: "Harden authentication flows",
    description: "Revoir les redirects, les controles serveur et les risques de privilege escalation.",
    status: TaskStatus.DONE,
    dueDate: "2026-05-12T09:00:00.000Z",
    completedAt: "2026-05-11T18:30:00.000Z",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "omar.kallel@demo.resilience.local",
    createdByEmail: "admin@demo.resilience.local",
    title: "Prepare delivery checklist and observability plan",
    description: "Formaliser les checks de release, les alertes minimales et la structure des retours d'incident.",
    status: TaskStatus.IN_PROGRESS,
    dueDate: "2026-05-19T09:00:00.000Z",
  },
  {
    projectKey: "l1-study-group-scheduler",
    studentEmail: "yassine.dridi@demo.resilience.local",
    createdByEmail: "supervisor.archi@demo.resilience.local",
    title: "Build weekly availability planner",
    description: "Construire le planning de creneaux avec disponibilites, conflits legers et recapitulatif de groupe.",
    status: TaskStatus.IN_PROGRESS,
    dueDate: "2026-05-23T10:00:00.000Z",
  },
] as const;

export const deliverables = [
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "rayan.haddad@demo.resilience.local",
    taskTitle: "Model support tickets in Prisma",
    title: "Prisma schema v1 for support domain",
    description: "Premier schema de tickets, commentaires et historique de statut.",
    submissionUrl: "https://submissions.demo.local/helpdesk/schema-v1",
    repositoryUrl: "https://github.demo.local/rayan-haddad/campus-helpdesk",
    status: DeliverableStatus.APPROVED,
    submittedAt: "2026-05-14T14:00:00.000Z",
    reviewedAt: "2026-05-15T08:30:00.000Z",
    reviewedByEmail: "supervisor.archi@demo.resilience.local",
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    taskTitle: "Design incident intake API",
    title: "Incident intake API contract",
    description: "Documentation des endpoints, payloads et regles de validation pour l'entree d'incidents.",
    submissionUrl: "https://submissions.demo.local/novacraft/intake-api-contract",
    repositoryUrl: "https://github.demo.local/mehdi-fekih/ops-hub-api",
    status: DeliverableStatus.IN_REVIEW,
    submittedAt: "2026-05-16T12:00:00.000Z",
    reviewedAt: null,
    reviewedByEmail: "contact@novacraft.demo.resilience.local",
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "leila.hammami@demo.resilience.local",
    taskTitle: "Harden authentication flows",
    title: "Auth and RBAC verification report",
    description: "Rapport de verification des flux auth, middleware, guards serveur et risques residuels.",
    submissionUrl: "https://submissions.demo.local/hardening/auth-rbac-report",
    repositoryUrl: "https://github.demo.local/leila-hammami/platform-hardening",
    status: DeliverableStatus.APPROVED,
    submittedAt: "2026-05-11T17:40:00.000Z",
    reviewedAt: "2026-05-12T09:15:00.000Z",
    reviewedByEmail: "supervisor.data@demo.resilience.local",
  },
] as const;

export const feedbacks = [
  {
    projectKey: "l1-campus-helpdesk",
    studentEmail: "rayan.haddad@demo.resilience.local",
    deliverableTitle: "Prisma schema v1 for support domain",
    membershipStudentEmail: "rayan.haddad@demo.resilience.local",
    authorEmail: "supervisor.archi@demo.resilience.local",
    source: FeedbackSource.SUPERVISOR,
    title: "Schema propre et bien pense",
    comment:
      "Bonne separation des responsabilites et une progression nette sur la modelisation. Il faut encore mieux expliciter les cas limites de transition de statut.",
    rating: 4,
  },
  {
    projectKey: "l2-novacraft-ops-hub",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    deliverableTitle: "Incident intake API contract",
    membershipStudentEmail: "mehdi.fekih@demo.resilience.local",
    authorEmail: "contact@novacraft.demo.resilience.local",
    source: FeedbackSource.COMPANY,
    title: "Tres bon sens des contraintes operations",
    comment:
      "Le cadrage des payloads est solide et montre une bonne comprehension du besoin metier. A renforcer: les cas de reprise en erreur et le suivi des SLA.",
    rating: 4,
  },
  {
    projectKey: "l3-autonomous-platform-hardening",
    studentEmail: "leila.hammami@demo.resilience.local",
    deliverableTitle: "Auth and RBAC verification report",
    membershipStudentEmail: "leila.hammami@demo.resilience.local",
    authorEmail: "supervisor.data@demo.resilience.local",
    source: FeedbackSource.SUPERVISOR,
    title: "Niveau d'autonomie confirme",
    comment:
      "La verification est rigoureuse, les risques sont bien cadres et les recommandations restent pragmatiques. C'est un livrable de niveau quasi professionnel.",
    rating: 5,
  },
] as const;

export const technicalScores = [
  {
    studentEmail: "rayan.haddad@demo.resilience.local",
    projectKey: "l1-campus-helpdesk",
    feedbackTitle: "Schema propre et bien pense",
    evaluatorEmail: "supervisor.archi@demo.resilience.local",
    category: "code_quality",
    score: 4,
    maxScore: 5,
    notes: "Bonne progression sur Prisma et les contraintes relationnelles.",
  },
  {
    studentEmail: "mehdi.fekih@demo.resilience.local",
    projectKey: "l2-novacraft-ops-hub",
    feedbackTitle: "Tres bon sens des contraintes operations",
    evaluatorEmail: "contact@novacraft.demo.resilience.local",
    category: "problem_solving",
    score: 4,
    maxScore: 5,
    notes: "API contract solide et vocabulaire metier bien compris.",
  },
  {
    studentEmail: "leila.hammami@demo.resilience.local",
    projectKey: "l3-autonomous-platform-hardening",
    feedbackTitle: "Niveau d'autonomie confirme",
    evaluatorEmail: "supervisor.data@demo.resilience.local",
    category: "technical_autonomy",
    score: 5,
    maxScore: 5,
    notes: "Tres bonne priorisation des risques et execution propre.",
  },
] as const;

export const maturityScores = [
  {
    studentEmail: "sarra.kefi@demo.resilience.local",
    projectKey: "l2-novacraft-ops-hub",
    evaluatorEmail: "supervisor.archi@demo.resilience.local",
    feedbackTitle: null,
    dimension: "communication",
    score: 4,
    maxScore: 5,
    notes: "Communication claire sur l'avancement et les dependances.",
  },
  {
    studentEmail: "leila.hammami@demo.resilience.local",
    projectKey: "l3-autonomous-platform-hardening",
    evaluatorEmail: "supervisor.data@demo.resilience.local",
    feedbackTitle: "Niveau d'autonomie confirme",
    dimension: "initiative",
    score: 5,
    maxScore: 5,
    notes: "Prise d'initiative, tri des priorites et execution tres mature.",
  },
  {
    studentEmail: "omar.kallel@demo.resilience.local",
    projectKey: "l3-autonomous-platform-hardening",
    evaluatorEmail: "admin@demo.resilience.local",
    feedbackTitle: null,
    dimension: "teamwork",
    score: 4,
    maxScore: 5,
    notes: "Coordonne bien la livraison et aide a garder un cap produit.",
  },
] as const;

export const certificates = [
  {
    referenceCode: "CERT-L1-RAYAN-2026",
    verificationCode: "VERIFY-RAYAN-2026-001",
    studentEmail: "rayan.haddad@demo.resilience.local",
    projectKey: "l1-campus-helpdesk",
    membershipStudentEmail: "rayan.haddad@demo.resilience.local",
    issuedByEmail: "supervisor.archi@demo.resilience.local",
    status: CertificateStatus.ISSUED,
    title: "Attestation de contribution projet pedagogique",
    summary: "Participation validee a la phase de modelisation et d'implementation du portail support campus.",
    issuedAt: "2026-05-16T10:00:00.000Z",
  },
  {
    referenceCode: "CERT-L2-MEHDI-DRAFT-2026",
    verificationCode: "VERIFY-MEHDI-2026-001",
    studentEmail: "mehdi.fekih@demo.resilience.local",
    projectKey: "l2-novacraft-ops-hub",
    membershipStudentEmail: "mehdi.fekih@demo.resilience.local",
    issuedByEmail: "contact@novacraft.demo.resilience.local",
    status: CertificateStatus.DRAFT,
    title: "Attestation de contribution projet entreprise",
    summary: "Brouillon d'attestation en preparation pour la contribution API du projet Ops Hub.",
    issuedAt: null,
  },
  {
    referenceCode: "CERT-L3-LEILA-2026",
    verificationCode: "VERIFY-LEILA-2026-001",
    studentEmail: "leila.hammami@demo.resilience.local",
    projectKey: "l3-autonomous-platform-hardening",
    membershipStudentEmail: "leila.hammami@demo.resilience.local",
    issuedByEmail: "admin@demo.resilience.local",
    status: CertificateStatus.ISSUED,
    title: "Attestation mission avancee autonomie professionnelle",
    summary: "Validation d'une mission de fiabilisation plateforme avec niveau d'autonomie eleve.",
    issuedAt: "2026-05-18T11:00:00.000Z",
  },
] as const;

export const portfolioItems = [
  {
    studentEmail: "rayan.haddad@demo.resilience.local",
    projectKey: "l1-campus-helpdesk",
    title: "Support domain schema and ticket workflow",
    summary: "Schema de donnees et flux de tickets pour un portail pedagogique de support.",
    description: "Travail focalise sur la modelisation de tickets, les transitions de statut et les fondations API.",
    demoUrl: "https://portfolio-demo.local/rayan/helpdesk",
    repositoryUrl: "https://github.demo.local/rayan-haddad/campus-helpdesk",
    isPublished: true,
    sortOrder: 1,
  },
  {
    studentEmail: "mehdi.fekih@demo.resilience.local",
    projectKey: "l2-novacraft-ops-hub",
    title: "Incident intake API for operations dashboard",
    summary: "API REST orientee incidents avec payloads qualifies et base de gestion de SLA.",
    description: "Contribution backend sur un vrai contexte operations B2B.",
    demoUrl: "https://portfolio-demo.local/mehdi/ops-hub",
    repositoryUrl: "https://github.demo.local/mehdi-fekih/ops-hub-api",
    isPublished: true,
    sortOrder: 1,
  },
  {
    studentEmail: "leila.hammami@demo.resilience.local",
    projectKey: "l3-autonomous-platform-hardening",
    title: "Authentication and platform hardening mission",
    summary: "Mission avancee de securisation auth/RBAC et de robustesse plateforme.",
    description: "Verification des flows sensibles, renforcement des guards et formalisation des risques residuels.",
    demoUrl: "https://portfolio-demo.local/leila/platform-hardening",
    repositoryUrl: "https://github.demo.local/leila-hammami/platform-hardening",
    isPublished: true,
    sortOrder: 1,
  },
] as const;
